export const REFRESHING_TOKEN = 'REFRESHING_TOKEN';
export const DONE_REFRESHING_TOKEN = 'DONE_REFRESHING_TOKEN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const SET_HEADER = 'SET_HEADER';

